name: 'Get report for all users in the enterprise'
description: 'Get a CSV report for all users in the enterprise'
author: 'Piotr Karpala'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-pat:
    description:
      'Classic user token with permissions to read: project, read:enterprise,
      read:org, user'
    required: true
  github-enterprise:
    description: 'The name of the enterprise to run the report for'
    required: true
  get-last-activity-date:
    description: 'Get the last activity date for each user'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  file:
    description: 'CSV file with the report'

runs:
  using: node20
  main: dist/index.js
